# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72c905f3d92201faba409645812b2243cfe1a6007fed7661c92e0455cf8d4cdaf6fa208874f97c85a5567deeb3f2ee51408e2fdf56fa2966b92651688acc1ced

test:
  secret_key_base: 6e945e8ca340a802191d65cf31305b31940914e71dd99a3e594f8e53fccfbc44693120aac34f878331f08ad69d6280467713a08241dedcfc4420e15f80fbebe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
